### ISSUE TITLE
Problems with usb storage

### ISSUE THREAD

**Issue by deantonious** [d1slact0r/gl-ar150-pineapple-firmware-builder#1]
I've compiled and flashed the pineapple firmware v2.4.1 and I find it impossible to mount the usb storage. Meanwhile with the v2.0.2 from https://github.com/SecurityAddicted/pineapple-ar150 eveything works fine. Any idea on how to solve this?

**Comment by d1slact0r** [comment]
Please use this:
https://github.com/d1slact0r/pineapple-firmware-builder
